### ISSUE TITLE
Everything is wrong

### ISSUE THREAD

**Issue by Joshua-Gordon** [Team1100/FRCPowerUp#1]
Robot.java
Line 27, "respected" instead of "respective"
Line 51, "every" instead of "ever"
Line 104, "is" instead of "in"

OI.java
Line 12,13, variables not documented
Line 32, "it's" instead of "its"
Line 40, "it's" instead of "its"

RobotMap.java
Line 4, "ports" instead of "port's"
Line everywhere, no comments on sections of constants

ExampleSubsystem.java
Line 33, "run" instead of "ran"

AttackThree.java
Line 8,9, variables not documented
Line 21,24, magic number
Line 24, loop not documented

Extreme3DPro.java
Line 8,9,10, variables not documented
Line 23,26, magic number
Line 26, loop not documented

XboxController.java
Line 68, "beadband" instead of "deadband"
Line 109, 111, "B" instead of "X"

**Comment by DaStinkingScaliwag** [comment]
Oof

**Comment by GrantPerkins** [comment]
Why in the world is this Very High Priority?

**Comment by thomashayden** [comment]
Why in the world would it not be Very High Priority?

**Comment by GrantPerkins** [comment]
It didn't seem to be much of an issue in FRCSteamworks, seeing as every class in the robot.input package is just pasted from there.

**Comment by Joshua-Gordon** [comment]
Times have changed.

**Comment by DaStinkingScaliwag** [comment]
"Line 32, "it's" instead of "its""

That comment was written BY WPILIBJ, how dare they have a typo!

**Comment by DaStinkingScaliwag** [comment]
Josh, the typos you pointed out in OI.java are not typos. Both usages of "it's" are correct, because they are supposed to be contractions for "it is".

**Comment by GrantPerkins** [comment]
When WPILib uses incorrect grammar :/

**Comment by thomashayden** [comment]
Better escalate to WPI

**Comment by DaStinkingScaliwag** [comment]
Do it, no balls

**Comment by DaStinkingScaliwag** [comment]
I am not going to doc each constant in the robot map.

**Comment by GrantPerkins** [comment]
Ok what is:

    private static final int P_0 = 0;
	private static final int P_1 = 1;
	private static final int P_2 = 2;
	private static final int P_3 = 3;
	private static final int P_4 = 4;
	private static final int P_5 = 5;
	private static final int P_6 = 6;
	private static final int P_7 = 7;

found in Robot Map.

**Comment by thomashayden** [comment]
I think those might be power reading for keeping track of voltages from the PDP

**Comment by thomashayden** [comment]
Additionally, I've been looking through their source but can't find where all the files are. I found a few, but I think most of them might just be from documentation or have just been passed from year to year. I did have every intent of making a pull request.

**Comment by GrantPerkins** [comment]
Is it actually a thing to JavaDoc "for" loops?

**Comment by thomashayden** [comment]
Not JavaDoc, but to have a small comment explaining what it's doing if it isn't clear

**Comment by DaStinkingScaliwag** [comment]
^ cool beans

**Comment by GrantPerkins** [comment]
Just pushed.

**Comment by GrantPerkins** [comment]
I appreciate you guys so diligently checking my work.

**Comment by DaStinkingScaliwag** [comment]
Thanks!

**Comment by thomashayden** [comment]
Anytime! Now you get to resolve the issue

**Comment by Joshua-Gordon** [comment]
The point of documenting a loop is that loops are often culprits in slow code, so it's nice to keep tabs on what they do. Same goes for recurses.
