### ISSUE TITLE
ChangeHeading Spins Infinitely

### ISSUE THREAD

**Issue by GrantPerkins** [Team1100/FRCPowerUp#10]
Randomly, the robot spins when different targets are assigned. This seems to occur more often when going in a negative change.

**Comment by ghost** [comment]
Checked in ChangeHeading to use PIDController methods. This allows native circular input ranges and should work better.

Be sure to test the robot on the bench (on blocks) to make sure the wheels spin the correct direction.

**Comment by tm1287** [comment]
I believe that this issue has been resolved.

**Comment by GrantPerkins** [comment]
In the auto I tested last night, the robot did some funky spinning
