### ISSUE TITLE
To do: Test Limelight, Implement it in Auto possibly w/ "save image" func.

### ISSUE THREAD

**Issue by GrantPerkins** [Team1100/FRCPowerUp#11]
We need to test Tejas's code to ensure it works, then we need to make a CenterOnCube command. Probably PID:wink:

**Comment by tm1287** [comment]
We also need to do something about cube detection in different lightings, as the HSV values change drastically in different environments.

**Comment by GrantPerkins** [comment]
That would include writing a "save image" function. Also, does the limelight software require wifi?

**Comment by tm1287** [comment]
You need to connect to the robot's network in order to stream the feed and adjust the settings.

**Comment by GrantPerkins** [comment]
Oh good. I was worried that we would be unable to change the settings during competitions

**Comment by tm1287** [comment]
When connected to the robot network, we can find a way to download the image stream from  http://10.11.00.11:5800 to tune the HSV values.

**Comment by zach-youssef** [comment]
Why are you two way better at this than we were?

**Comment by Joshua-Gordon** [comment]
I'm proud.

**Comment by GrantPerkins** [comment]
Still to do: figure out why Limelight randomly disconnects and make it stop doing that, write CenterOnCubeCommand

**Comment by tm1287** [comment]
Refer to new limelight issue.
