### ISSUE TITLE
To do: Implement TensorFlow to Find Perfect HSV Values

### ISSUE THREAD

**Issue by GrantPerkins** [Team1100/FRCPowerUp#12]
We need to earn a masters in cs by using machine learning to perfect our vision code. This ain't a meme fams

**Comment by GrantPerkins** [comment]
Oof ow ouch my bones dis aint be a meme we need this in our lives

**Comment by tm1287** [comment]
We can also try using Amazon's new DeepLens that uses AWS. It's pretty cool and seems relatively easier to use.

**Comment by GrantPerkins** [comment]
Ye but thats not officially CodinGame.com endorsed

**Comment by zach-youssef** [comment]
I love this. Don't give up!

**Comment by Joshua-Gordon** [comment]
Without joking, I fully encourage you to try to put machine learning in the code. You have my contact info if you need any help with it.

**Comment by tm1287** [comment]
Seems like an off season thing though.

**Comment by GrantPerkins** [comment]
Another time.
