### ISSUE TITLE
What does the pneumatic climber do? How is it different from the normal climber?

### ISSUE THREAD

**Issue by snowpuppy** [Team1100/FRCPowerUp#25]
https://github.com/Team1100/FRCPowerUp/blob/8a3102e27a0078a247a2cf4e9339d2072609a9ef/src/org/usfirst/frc/team1100/robot/subsystems/PneumaticClimber.java#L11

**Comment by GrantPerkins** [comment]
We have a new second stage to the elevator for lifting a cube into the scale. It isn't quite a "climber", but it does use pneumatics.
