### ISSUE TITLE
Implement Tensor Flow

### ISSUE THREAD

**Issue by tm1287** [Team1100/FRCPowerUp#38]
We need it...

**Comment by tm1287** [comment]
Or as an alternative, integrate Amazon SageMaker

**Comment by Pentation** [comment]
Sagemaker uses tensorflow

**Comment by GrantPerkins** [comment]
I want pure tensorflow though, actually writing python code to do it. I don't want to be working on that high of a level anymore (i.e. limelight)

**Comment by Pentation** [comment]
We need to remount the prox sensor first. But yeah that would make it easier to work with in the long run

**Comment by tm1287** [comment]
What do you guys think is the best way to get a library of power cube training images?

**Comment by thomashayden** [comment]
Unless any other team has a bunch of images, just get a camera, a power cube, and start taking a bunch of pictures. If you need images with the same settings as the one on the robot, either use the robot, or a spare camera thats the same and run it through the robot code.

**Comment by Joshua-Gordon** [comment]
opencv has a createsamples utility. Read this: https://docs.opencv.org/3.3.0/dc/d88/tutorial_traincascade.html and ask any questions you have.

**Comment by GrantPerkins** [comment]
We should plug the usb camera into a laptop, take a ton of pics of the cube, run opencv code on them to get centerx. Train off of the images+center x value.

**Comment by tm1287** [comment]
I think that's the only way to do it

**Comment by GrantPerkins** [comment]
I have a Wolfram Language subscription, if we want to do that. Its really high level, but it would be easy.

**Comment by Pentation** [comment]
I think I found a collection of a lot of images online zipped so we could just use online stuff. It would be a lot more efficient

**Comment by GrantPerkins** [comment]
Link?

**Comment by tm1287** [comment]
http://www.team358.org/history/2018/images.php?directory=kickoff&page=0

https://photos.google.com/share/AF1QipOX-yCi3H_zFcXa4796pTggbcVoS3bQ1JdOtiXA1oYg4X8cXHSFs_yGnZJLUgr2xQ?key=VFRTbFN1MUt6VHVvbkZvdWxZZ2RBd0hLMHF1VWd3

**Comment by Pentation** [comment]
Also this: https://drive.google.com/drive/folders/1ZjFNAZhz-0GDHSjJMIakqACllZqrg7DV

It has around a 1000 images for neural network training

**Comment by tm1287** [comment]
Compiled 1466 usable images here:
https://drive.google.com/drive/folders/124WklCUnX_fOi2XyC280PQjLmDO-uU4E?usp=sharing
